# Generated by Django 2.2.24 on 2021-06-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'contact_messages',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('title', models.CharField(max_length=100, verbose_name='Degree')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Linkedin Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Photo')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
                'ordering': ('id',),
            },
        ),
    ]
