# Generated by Django 2.1 on 2018-11-22 21:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('email_address', models.CharField(max_length=60, verbose_name='Email Address')),
                ('content', models.TextField(verbose_name='Comment')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Approval Status')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Post Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Post Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Picture')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'post'}, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='category.Category', verbose_name='Post Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Post', verbose_name='Post'),
        ),
    ]
