# Generated by Django 2.1 on 2018-11-22 21:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Service Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('meta_description', models.TextField(verbose_name='Meta Description')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Service Content')),
                ('image', models.ImageField(upload_to='', verbose_name='Service Picture')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'service'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='category.Category', verbose_name='Service Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['title'],
            },
        ),
    ]
