# Generated by Django 2.1 on 2019-03-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
