# Generated by Django 2.1 on 2019-03-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('id',), 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
