# Generated by Django 2.1 on 2018-11-22 21:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Portfolio Title')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Meta Description')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Portfolio Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Portfolio Image')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'portfolio'}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='category.Category', verbose_name='Portfolio Category')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'db_table': 'portfolios',
                'ordering': ['-published_at'],
            },
        ),
    ]
