# Generated by Django 2.1 on 2019-03-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('key',), 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
    ]
